apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sts-virtual-service
spec:
  hosts:
  - sts.ecomm.com
  gateways:
  - ecomm-gateway.istio-system.svc.cluster.local
  http:
    - route:
      - destination:
          host: sts-service
          port:
            number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-virtual-service
spec:
  hosts:
  - orders.ecomm.com
  gateways:
  - ecomm-gateway.istio-system.svc.cluster.local
  http:
    - route:
      - destination:
          host: orders-service
          port:
            number: 80           
